### PR TITLE
fix protected names in conflict_target

### PR DESCRIPTION
**Pull request by michaelst**
### Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Features include unit/acceptance tests

### CODE REVIEW

**Comment by zachdaniel** [comment]
What’s an example of what this fixes?

**Comment by michaelst** [comment]
> What’s an example of what this fixes?

I have a table with a column name of table, table was used in an identity as an upsert_target

**Comment by zachdaniel** [comment]
oh. wow. Thanks. Good thing you didn't have an attribute called `DROP TABLE table`.

**Comment by michaelst** [comment]
little bobby tables 😉

**Pull request merged**
