### PR TITLE
Fix migration generator extensions in multiple repos

### PR DESCRIPTION
**Pull request by rgraff**
### Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Features include unit/acceptance tests

### CODE REVIEW

**Comment by rgraff** [comment]
Fixes #213

**Comment by zachdaniel** [comment]
🔥

**Comment by zachdaniel** [comment]
That was fast!

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
