### PR TITLE
fix: fix fragment processing broken

### PR DESCRIPTION
**Pull request by basicBrogrammer**
Let me know what kind of testing needs to be done and I can see what I can do. 

### Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Features include unit/acceptance tests

### CODE REVIEW

**Comment by zachdaniel** [comment]
I think a simple test in `filter_test.exs` that does something like `Ash.Query.filter(Post, fragment("? = ?", post.id, ^post.id)` should do it.

**Comment by basicBrogrammer** [comment]
> I think a simple test in `filter_test.exs` that does something like `Ash.Query.filter(Post, fragment("? = ?", post.id, ^post.id)` should do it.

I couldn't do ID. I got an error about postgrex expecting a binary when it received a string version of the id. So I used the title

**Comment by zachdaniel** [comment]
Ah, all good. In the future, you can do `type(^post.id, :uuid)`.

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
