### PR TITLE
Add nulls_distinct option to CustomIndex

### PR DESCRIPTION
**Pull request by nallwhy**
### Contributor checklist

- [ ] Bug fixes include regression tests
- [x] Features include unit/acceptance tests

This is a duplicate of PR #175, but it seems that the mentioned PR is no longer progressing, so I am posting it again.

The DSL documentation appears to be automatically generated. How can I update it?

### CODE REVIEW

**Review by zachdaniel — APPROVED** [review]

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Comment by zachdaniel** [comment]
👋 this looks good, but after running project checks there are a few things to address. 

1. please run `mix spark.formatter` and `mix spark.cheat_sheets` to regenerate those files.
2. The migration generator thinks that it needs to generate migrations in test. This is because, when reading the snapshot files, we aren't setting the default value of `nulls_distinct` to `false`, that way old custom indexes don't appear to have changed.

**Review by zachdaniel — CHANGES_REQUESTED** [review]
👋 this looks good, but after running project checks there are a few things to address.

please run mix spark.formatter and mix spark.cheat_sheets to regenerate those files.
The migration generator thinks that it needs to generate migrations in test. This is because, when reading the snapshot files, we aren't setting the default value of nulls_distinct to false, that way old custom indexes don't appear to have changed.

**Comment by zachdaniel** [comment]
We will need to add `|> Map.put_new(:nulls_distinct, false)` here https://github.com/ash-project/ash_postgres/blob/main/lib/migration_generator/migration_generator.ex#L2990

**Comment by zachdaniel** [comment]
Hmm...for some reason, migrations still need to be generated. To test this you can run `mix test.generate_migrations --dry-run` to see what it thinks it needs to migrate. If it's not related to your changes let me know.

https://github.com/ash-project/ash_postgres/actions/runs/8233885967/job/22515144134?pr=221

**Comment by nallwhy** [comment]
Sorry, I didn't get it.
When I run `mix test.generate_migrations --dry-run`, it returns below message.
It does not seem to be related to this PR.

```
Extension Migrations: 
No extensions to install

Generating Tenant Migrations: 
No tenant changes detected, so no migrations or snapshots have been created.

Generating Migrations:
defmodule AshPostgres.TestRepo.Migrations.MigrateResources19 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:posts, [:uniq_custom_one, :uniq_custom_two],
                     name: "posts_uniq_custom_one_uniq_custom_two_index"
                   )
  end

  def down do
    create index(:posts, [:uniq_custom_one, :uniq_custom_two],
             unique: true,
             concurrently: true,
             where: "type = 'sponsored'"
           )
  end
end
defmodule AshPostgres.TestRepo.Migrations.MigrateResources19 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:posts, [:uniq_custom_one, :uniq_custom_two],
             unique: true,
             concurrently: true,
             where: "type = 'sponsored'"
           )
  end

  def down do
    drop_if_exists index(:posts, [:uniq_custom_one, :uniq_custom_two],
                     name: "posts_uniq_custom_one_uniq_custom_two_index"
                   )
  end
end
```

**Comment by zachdaniel** [comment]
I'm pretty sure it is related to this PR, I think its the diffing of custom indexes.

Try this:

```elixir
   nulls_distinct: [
       type: :boolean,
       doc: "specify whether null values should be considered distinct for a unique index.",
       default: false
     ],
```

**Comment by nallwhy** [comment]
Oh, now I understand it. Thanks!

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
