### PR TITLE
improvement: add DataCase creation for igniter installer

### PR DESCRIPTION
**Pull request by ibarakaiev**
### Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Features include unit/acceptance tests

This PR sets up `DataCase` for testing purposes, unless it already exists, and adds `test` to `elixirc_paths` in `mix.exs` unless `elixirc_paths` are already defined. For fresh Mix projects, this will do both; for existing Phoenix projects, nothing will happen. This makes it possible to use AshPostgres out of the box even in tests.

Note: this PR is pending https://github.com/ash-project/igniter/pull/38 and https://github.com/ash-project/igniter/pull/37, so it is marked as a draft.

### CODE REVIEW

**Comment by ibarakaiev** [comment]
One side effect of this change is that, when running `apply_and_fetch_dependencies/2`, the changes to `elixirc_paths` and the new functions show up, which appear a bit confusing when only dependencies need to be installed.

**Comment by zachdaniel** [comment]
Will come back to this once the main installer is merged.

**Comment by zachdaniel** [comment]
Closing in favor of #346

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request closed without merging**
